defaults: &defaults
  spotify:
    client_id: abc
    client_secret: abc
    redirect_uri: "https://amplifyapp.ca/spotify_callback"

development:
  <<: *defaults
  secret_key_base: abc

test:
  <<: *defaults
  secret_key_base: abc
  spotify:
    client_id: fakeauthcode
    client_secret: fakeauthcode
    redirect_uri: "https://amplifyapp.ca/spotify_callback"

production:
  <<: *defaults
  secret_key_base: just_for_compilation

staging:
  <<: *defaults
  secret_key_base: just_for_compilation
